# Sowing Success: How Machine Learning Helps Farmers Select the Best Crops

![Farmer in a field](farmer_in_a_field.jpg)

Measuring essential soil metrics such as nitrogen, phosphorous, potassium levels, and pH value is an important aspect of assessing soil condition. However, it can be an expensive and time-consuming process, which can cause farmers to prioritize which metrics to measure based on their budget constraints.

Farmers have various options when it comes to deciding which crop to plant each season. Their primary objective is to maximize the yield of their crops, taking into account different factors. One crucial factor that affects crop growth is the condition of the soil in the field, which can be assessed by measuring basic elements such as nitrogen and potassium levels. Each crop has an ideal soil condition that ensures optimal growth and maximum yield.

A farmer reached out to you as a machine learning expert for assistance in selecting the best crop for his field. They've provided you with a dataset called `soil_measures.csv`, which contains:

- `"N"`: Nitrogen content ratio in the soil
- `"P"`: Phosphorous content ratio in the soil
- `"K"`: Potassium content ratio in the soil
- `"pH"` value of the soil
- `"crop"`: categorical values that contain various crops (target variable).

Each row in this dataset represents various measures of the soil in a particular field. Based on these measurements, the crop specified in the `"crop"` column is the optimal choice for that field.  

In this project, you will build multi-class classification models to predict the type of `"crop"` and identify the single most importance feature for predictive performance.

In [26]:
# All required libraries are imported here for you.
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

# Load the dataset
crops = pd.read_csv("soil_measures.csv")

# Write your code here
crops.head(10)

    N   P   K        ph  crop
0  90  42  43  6.502985  rice
1  85  58  41  7.038096  rice
2  60  55  44  7.840207  rice
3  74  35  40  6.980401  rice
4  78  42  42  7.628473  rice
5  69  37  42  7.073454  rice
6  69  55  38  5.700806  rice
7  94  53  40  5.718627  rice
8  89  54  38  6.685346  rice
9  68  58  38  6.336254  rice

## Data Analysis

In [27]:
crops.isna().sum().sort_values()

N       0
P       0
K       0
ph      0
crop    0
dtype: int64

In [28]:
crops.isnull().sum().sort_values()

N       0
P       0
K       0
ph      0
crop    0
dtype: int64

In [29]:
crops['crop'].unique()

array(['rice', 'maize', 'chickpea', 'kidneybeans', 'pigeonpeas',
       'mothbeans', 'mungbean', 'blackgram', 'lentil', 'pomegranate',
       'banana', 'mango', 'grapes', 'watermelon', 'muskmelon', 'apple',
       'orange', 'papaya', 'coconut', 'cotton', 'jute', 'coffee'],
      dtype=object)

In [30]:
crops.describe()

                 N            P            K           ph
count  2200.000000  2200.000000  2200.000000  2200.000000
mean     50.551818    53.362727    48.149091     6.469480
std      36.917334    32.985883    50.647931     0.773938
min       0.000000     5.000000     5.000000     3.504752
25%      21.000000    28.000000    20.000000     5.971693
50%      37.000000    51.000000    32.000000     6.425045
75%      84.250000    68.000000    49.000000     6.923643
max     140.000000   145.000000   205.000000     9.935091

## Data Preprocessing

In [31]:
X = crops[['N','P','K','ph']]
y = crops['crop']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

print(f"The Shape of X_train is :{X_train.shape}")
print(f"The Shape of X_test is :{X_test.shape}")
print(f"The Shape of Y_train is :{y_train.shape}")
print(f"The Shape of y_test is :{y_test.shape}")

The Shape of X_train is :(1760, 4)
The Shape of X_test is :(440, 4)
The Shape of Y_train is :(1760,)
The Shape of y_test is :(440,)

##  Model Feature Selection

In [32]:
feature_pefromance = {}
LogReg = LogisticRegression(multi_class='multinomial')

for features in ['N','P','K','ph']:
    LogReg.fit(X_train[[features]], y_train)
    y_pred = LogReg.predict(X_test[[features]])

    f1 = metrics.f1_score(y_test,y_pred,average='weighted')

    feature_pefromance[features] =  f1
    print(f"F1-Score for {features}:{f1}")

F1-Score for N:0.09149868209906838
F1-Score for P:0.14761942909728204
F1-Score for K:0.23896974566001802
F1-Score for ph:0.04532731061152114

In [33]:
best_predictive_feature = {"K":feature_pefromance["K"]}
best_predictive_feature

{'K': 0.23896974566001802}