In this chapter, we will see how to fill gaps in our data. Missing data can be due to :

1. Data not being collected properly
2. Collection and Managment errors
3. Data intentionally being ommited
4. Could be created due to transformation of the data
and the list goes on.........

Missing data can lead to many problems down stream  like :

1. ML Models cannot perform on missing data
2. Missing data may be sign of wider data issue
to name some.

We can use the `df.info()`, which will provide a brief overview of the dataset.But becomes limited as the dataset goes.


Instead we can use `df.isnull()` , method to get the null values in the entire column or the entire dataset.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [7]:
df = pd.read_csv('data/loans.csv')
df.head()

,customer_id,disbursed_amount,interest,market,employment,time_employed,householder,income,date_issued,target,loan_purpose,number_open_accounts,date_last_payment,number_credit_lines_12
0,0,23201.5,15.4840,C,Teacher,<=5 years,RENT,84600.0,2013-06-11,0,Debt consolidation,4.0,2016-01-14,NaN
1,1,7425.0,11.2032,B,Accountant,<=5 years,OWNER,102000.0,2014-05-08,0,Car purchase,13.0,2016-01-25,NaN
2,2,11150.0,8.5100,A,Statistician,<=5 years,RENT,69840.0,2013-10-26,0,Debt consolidation,8.0,2014-09-26,NaN
3,3,7600.0,5.8656,A,Other,<=5 years,RENT,100386.0,2015-08-20,0,Debt consolidation,20.0,2016-01-26,NaN
4,4,31960.0,18.7392,E,Bus driver,>5 years,RENT,95040.0,2014-07-22,0,Debt consolidation,14.0,2016-01-11,NaN

In [9]:
print(df.isnull())

      customer_id  disbursed_amount  interest  market  employment  \
0           False             False     False   False       False
1           False             False     False   False       False
2           False             False     False   False       False
3           False             False     False   False       False
4           False             False     False   False       False
...           ...               ...       ...     ...         ...
9995        False             False     False   False       False
9996        False             False     False   False       False
9997        False             False     False   False       False
9998        False             False     False   False       False
9999        False             False     False   False       False

      time_employed  householder  income  date_issued  target  loan_purpose  \
0             False        False   False        False   False         False
1             False        False   False        False   False         False
2             False        False   False        False   False         False
3             False        False   False        False   False         False
4             False        False   False        False   False         False
...             ...          ...     ...          ...     ...           ...
9995          False        False   False        False   False         False
9996          False        False   False        False   False         False
9997          False        False   False        False   False         False
9998          False        False   False        False   False         False
9999          False        False   False        False   False         False

      number_open_accounts  date_last_payment  number_credit_lines_12
0                    False              False                    True
1                    False              False                    True
2                    False              False                    True
3                    False              False                    True
4                    False              False                    True
...                    ...                ...                     ...
9995                 False              False                    True
9996                 False              False                    True
9997                 False              False                    True
9998                 False              False                    True
9999                 False              False                    True

[10000 rows x 14 columns]

In [6]:
print(df.notnull())

      hour_of_day  cash_type  money  coffee_name  Time_of_Day  Weekday  \
0            True       True   True         True         True     True
1            True       True   True         True         True     True
2            True       True   True         True         True     True
3            True       True   True         True         True     True
4            True       True   True         True         True     True
...           ...        ...    ...          ...          ...      ...
3542         True       True   True         True         True     True
3543         True       True   True         True         True     True
3544         True       True   True         True         True     True
3545         True       True   True         True         True     True
3546         True       True   True         True         True     True

      Month_name  Weekdaysort  Monthsort  Date  Time
0           True         True       True  True  True
1           True         True       True  True  True
2           True         True       True  True  True
3           True         True       True  True  True
4           True         True       True  True  True
...          ...          ...        ...   ...   ...
3542        True         True       True  True  True
3543        True         True       True  True  True
3544        True         True       True  True  True
3545        True         True       True  True  True
3546        True         True       True  True  True

[3547 rows x 11 columns]

In [10]:
print(df['loan_purpose'].isnull())

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Name: loan_purpose, Length: 10000, dtype: bool

## Dealing with missing values:

When the missing values are not random, then we can use litwise deletion.
we can use the `df.dropna(subset=['Column_name'])`, this function will drop the rows that contain any Na values.

In [11]:
df.dropna()

,customer_id,disbursed_amount,interest,market,employment,time_employed,householder,income,date_issued,target,loan_purpose,number_open_accounts,date_last_payment,number_credit_lines_12
50,50,9100.0,16.0923,D,Nurse,<=5 years,RENT,28800.0,2015-12-25,0,Debt consolidation,21.0,2016-01-25,2.0
111,111,14250.0,13.5333,C,Software developer,>5 years,RENT,118800.0,2015-12-04,0,Debt consolidation,11.0,2010-12-05,2.0
116,116,10000.0,10.6764,B,Teacher,>5 years,MORTGAGE,38000.0,2015-12-23,0,Debt consolidation,10.0,2014-04-23,4.0
131,131,7760.0,8.4051,B,Bus driver,>5 years,MORTGAGE,39200.0,2015-12-19,0,Debt consolidation,15.0,2015-10-14,1.0
278,278,15246.0,17.2809,E,Nurse,>5 years,MORTGAGE,91665.0,2015-12-27,0,Debt consolidation,15.0,2016-01-06,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9858,9858,1674.0,13.8105,C,Nurse,>5 years,MORTGAGE,36860.0,2015-12-04,0,Debt consolidation,18.0,2016-01-11,2.0
9868,9868,20680.0,14.9477,D,Civil Servant,<=5 years,RENT,49500.0,2015-12-21,0,Debt consolidation,14.0,2014-01-02,2.0
9901,9901,11350.5,10.3224,B,Teacher,>5 years,MORTGAGE,84000.0,2015-12-08,0,Debt consolidation,7.0,2016-01-11,1.0
9983,9983,5820.0,5.7408,A,Bus driver,>5 years,MORTGAGE,133950.0,2015-12-13,0,Other,17.0,2015-12-25,3.0
9992,9992,1470.0,12.5900,C,Statistician,<=5 years,RENT,23660.0,2015-12-19,0,Debt consolidation,6.0,2016-01-24,1.0

Drawbacks of litwise deletion:

1. It delete valid data points
2. Relies on randomness
3. Reduces information


The problem with deletion is as the name suggests , data gets removed and hence that data is lost. This can be of huge implications when we are building ML Models where data quality and data quantity is very much essential.

Instead of this we can replace the values with some preferd value
using `df.fillna(value='Default Value', inplace=True)`. This function will replace the values the `NA` values with the already provided values.

In [12]:
df.fillna(value='None', inplace=True)

/var/folders/zb/bl3vjblx59ggp4ygks32q_7r0000gn/T/ipykernel_43458/1573829081.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'None' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.fillna(value='None', inplace=True)

Similiar as seen above ,we can expand this thought to include other forms of data like:

`Categorical columns`: Replace missing values with the most common occuring value or with a string that flags missing values such as 'None'.

`Numeric Columns`: Replace the missing values with a sutiable value.

The suitable value may depend on what is required . In general cases we will make use of the central tendency i.e `mean` and `median`.Use of these central tendency functions should be carefully done as they may lead to data bias and incorrect error staistics.