* Sklearn Ingests data that is numeric and has not missing values.
* In real world data is sometimes messy hence we need to preprocess the data into required standards.

One method is creating Dummy Variables: We can split categorical variables into seperate columns and create dummy_variables.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('data/music_clean.csv')
df.head(10)

,Unnamed: 0,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,genre
0,36506,60.0,0.896000,0.726,214547.0,0.177,0.000002,0.1160,-14.824,0.0353,92.934000,0.618,1
1,37591,63.0,0.003840,0.635,190448.0,0.908,0.083400,0.2390,-4.795,0.0563,110.012000,0.637,1
2,37658,59.0,0.000075,0.352,456320.0,0.956,0.020300,0.1250,-3.634,0.1490,122.897000,0.228,1
3,36060,54.0,0.945000,0.488,352280.0,0.326,0.015700,0.1190,-12.020,0.0328,106.063000,0.323,1
4,35710,55.0,0.245000,0.667,273693.0,0.647,0.000297,0.0633,-7.787,0.0487,143.995000,0.300,1
5,35111,62.0,0.010800,0.743,243333.0,0.670,0.070200,0.2200,-4.547,0.0293,110.832000,0.934,1
6,35594,58.0,0.001070,0.500,207173.0,0.836,0.000040,0.1970,-6.165,0.0454,90.011000,0.410,1
7,37473,74.0,0.076400,0.686,200467.0,0.783,0.000000,0.1630,-4.977,0.1190,119.952961,0.814,1
8,37418,64.0,0.002720,0.235,227296.0,0.860,0.096900,0.3880,-2.842,0.0561,127.788000,0.342,1
9,36605,55.0,0.122000,0.500,173773.0,0.854,0.000000,0.0794,-5.151,0.0945,94.960000,0.404,1

In [3]:
music_dummies = pd.get_dummies(df['genre'], drop_first=True)
music_dummies.head(10)

      1
0  True
1  True
2  True
3  True
4  True
5  True
6  True
7  True
8  True
9  True

In [5]:
music_dummies = pd.concat([df, music_dummies], axis=1)
music_dummies = music_dummies.drop("genre",axis=1)

## Handling Missing data

In [9]:
df.isna().sum().sort_values()

Unnamed: 0          0
popularity          0
acousticness        0
danceability        0
duration_ms         0
energy              0
instrumentalness    0
liveness            0
loudness            0
speechiness         0
tempo               0
valence             0
genre               0
dtype: int64

In [10]:
music_df = df.dropna(subset=['acousticness','danceability'])
music_df.isna().sum().sort_values()

Unnamed: 0          0
popularity          0
acousticness        0
danceability        0
duration_ms         0
energy              0
instrumentalness    0
liveness            0
loudness            0
speechiness         0
tempo               0
valence             0
genre               0
dtype: int64

### Imputing Values
* Imputation- use subject-matter expertise to replace missing data with educated guesses.
* Common to use the mean
* Can also use the median or another value.
* For categorical values,we typically use the most frequent value- the mode.
* Must split our data first , to avoid data leakage.

In [17]:
from sklearn.impute import SimpleImputer
X_cat = music_df["genre"].values.reshape(-1,1)
X_num = music_df.drop(["genre","popularity"], axis=1).values
y = music_df["popularity"].values

X_train_cat, X_test_cat , y_train , y_test = train_test_split(X_num,y, test_size=0.2,
random_state=12)
X_train_num, X_test_num , y_train , y_test = train_test_split(X_num,y, test_size=0.2,
random_state=12)

imp_cat = SimpleImputer(strategy='most_frequent')
X_train_cat = imp_cat.fit_transform(X_train_cat)
X_test_cat = imp_cat.transform(X_test_cat)

In [ ]:
# Numerical data imputation
imp_num = SimpleImputer()
X_train_num = imp_num.fit_transform(X_train_num)
X_test_num = imp_num.transform(X_test_num)
X_train = np.append(X_train_num, X_train_cat, axis=1)
X_test = np.append(X_test_num, X_train_cat, axis=1)

In [ ]:
# Import modules
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

# Instantiate an imputer
imputer = SimpleImputer()

# Instantiate a knn model
knn = KNeighborsClassifier(n_neighbors=3)

# Build steps for the pipeline
steps = [("imputer", imputer), 
         ("knn", knn)]

steps = [("imputer", imp_mean),
        ("knn", knn)]

# Create the pipeline
pipeline = Pipeline(steps)

# Fit the pipeline to the training data
pipeline.fit(X_train, y_train)

# Make predictions on the test set
y_pred = pipeline.predict(X_test)

# Print the confusion matrix
print(confusion_matrix(y_test, y_pred))

## Scalling and Centering

* Scalling involves that we keep the values in a specific range.
* Subtract the mean and divide by variance:
  * All features are centered around zeor and have a variance of one.
  * This is called standardization 
* Can also subtract the minimum and divide by the range
  * Minimum zero and maximum one

In [24]:
from sklearn.preprocessing import StandardScaler
X = df.drop(["genre"], axis=1).values
y = df["genre"].values

X_train, X_test , y_train , y_test = train_test_split(X,y, test_size=0.2,
random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

print(np.mean(X),np.std(X))
print(np.mean(X_train_scaled), np.std(X_train_scaled))

20666.582585618085 68890.98734103922
3.5971225997855074e-16 0.9999999999999996

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline


steps = [('scaler',StandardScaler()),
        'knn',KNeighborsClassifier(n_neighbors=6)]

pipeline = Pipeline(steps)
X_train, X_test , y_train , y_test = train_test_split(X,y, test_size=0.2,
random_state=21)

knn_scaled = pipeline.fit(X_train,y_train)
y_pred = knn_scaled.predict(X_test)
print(knn_scaled.score(X_test,y_test))

### Selection of Model
* Each model has is respecitve metrics and accuracy scores , hence to select a particular model based on its metrics.

In [ ]:
# Note this code is only for show and will not run
models = {"Linear Regression": LinearRegression(), "Ridge": Ridge(alpha=0.1), "Lasso": Lasso(alpha=0.1)}
results = []

# Loop through the models' values
for model in models.values():
  kf = KFold(n_splits=6, random_state=42, shuffle=True)
  
  # Perform cross-validation
  cv_scores = cross_val_score(model, X_train, y_train, cv=kf)
  
  # Append the results
  results.append(cv_scores)
  
# Create a box plot of the results
plt.boxplot(results, labels=models.keys())
plt.show()


# Import root_mean_squared_error
from sklearn.metrics import root_mean_squared_error

for name, model in models.items():
  # Fit the model to the training data
  model.fit(X_train_scaled, y_train)
  
  # Make predictions on the test set
  y_pred = model.predict(X_test_scaled)
  
  # Calculate the test_rmse
  test_rmse = root_mean_squared_error(y_test, y_pred)
  print("{} Test Set RMSE: {}".format(name, test_rmse))

In [ ]:
# Create models dictionary
models = {"Logistic Regression": LogisticRegression(), "KNN": KNeighborsClassifier(), "Decision Tree Classifier": DecisionTreeClassifier()}
results = []

# Loop through the models' values
for model in models.values():
  
  # Instantiate a KFold object
  kf = KFold(n_splits=6, random_state=12, shuffle=True)
  
  # Perform cross-validation
  cv_results = cross_val_score(model, X_train_scaled, y_train, cv=kf)
  results.append(cv_results)
plt.boxplot(results, labels=models.keys())
plt.show()

In [ ]:
# Create steps
steps = [("imp_mean", SimpleImputer()), 
         ("scaler", StandardScaler()), 
         ("logreg", LogisticRegression())]

# Set up pipeline
pipeline = Pipeline(steps)
params = {"logreg__solver": ["newton-cg", "saga", "lbfgs"],
         "logreg__C": np.linspace(0.001, 1.0, 10)}

# Create the GridSearchCV object
tuning = GridSearchCV(pipeline, param_grid=params)
tuning.fit(X_train, y_train)
y_pred = tuning.predict(X_test)

# Compute and print performance
print("Tuned Logistic Regression Parameters: {}, Accuracy: {}".format(tuning.best_params_, tuning.score(X_test, y_test)))